apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nitro-shared
  namespace: nitro
  labels:
    app: nitro-shared
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
